version: "3"
services:
  postgres:
    image: postgres:12
    ports:
      - "45432:5432"
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test


